### ISSUE TITLE
Can you provide a basic example?

### ISSUE THREAD

**Issue by pepperav** [stm32duino/S2-LP#10]
Hello Carlo,
thank you for your work.

I'm pretty new about this stuff so is possible to add an example for send/receive packet using this library?

Thank you

**Comment by fpistm** [comment]
Hi @pepperav 
all API are described here with some example code.

You can also refers to this example:
https://github.com/stm32duino/X-NUCLEO-S2915A1/blob/master/examples/X_NUCLEO_S2915A1_HelloWorld/X_NUCLEO_S2915A1_HelloWorld.ino
