### ISSUE TITLE
Possible bug related to SQI/PQI check

### ISSUE THREAD

**Issue by samuelsd1** [stm32duino/S2-LP#9]
I am currently trying to write S2LP driver for STM32, and stumbled upon the following code:

S2LP.cpp, lines 194-196
```c++
/* Enable SQI */
S2LPRadioSetPqiCheck(0x00);
S2LPRadioSetPqiCheck(S_ENABLE);
```

Comment says "EnableSQI", but the code enables Pqi and not Sqi.
Also first line `S2LPRadioSetPqiCheck(0x00);` seems to try doing something else.
After reading through STM32 P2P app sample code, I think you meant to set the Pqi threshold.

Another problem - is that I could not find the `S2LP_RADIO_QI_SetPQIThreshold` and `S2LP_RADIO_QI_SetSQIThreshold` function in your codebase, while they are present in the updated driver provided by STM32 (Version 1.3.2)

Apart from these, I think youv'e done great work with the driver.
Sadly STM does not provide too much documentation for S2LP, so I use your code as documentation 😄

**Comment by cparata** [comment]
Hi @samuelsd1 ,
basically the comment is wrong. I meant "Enable the PQI (Preamble Quality Indicator)". The first call should be to be sure to reset the settings and the second one to enable it. I started the porting from the S2-LP_DK v1.3.1 and in this driver version there were not APIs to set the PQI threshold. So, I will update the code to fix the wrong comment. Any contribution to improve the library is welcome.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Fix with https://github.com/stm32duino/S2-LP/commit/bf2afa9cd655cd01a6bb5db8cbe9934f334b7007
